name: CI ALL
on:
  release:
    types:
      - published

jobs:

  build:
    name: Build <App name>
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name : machine echo $HOME
        run : "echo $HOME"
      - name : machine ls $HOME
        working-directory : "."
        run : "ls -la $HOME"
      - name: Install dependencies
        run: yarn
      - name: Install dependencies
        run: ls
      - name: Build
        run: yarn package
