name: CI
on: [push]
jobs:
  build:
    name: macos-ci
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: package # will run `yarn test` command
