name: CI ALL
on: [push]

jobs:

  build:
    name: Build <App name>
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: "ls "
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name : machine echo $HOME
        run : "echo $HOME"
      - name : machine ls $HOME
        working-directory : "."
        run : "ls -la $HOME"
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn package
