name: CI ALL
on:
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}

jobs:
  build_on_mac:
    name: Build Gosuto on Mac
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: 'ls '
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '18.10.x'
      - name: machine echo $HOME
        run: 'echo $HOME'
      - name: Install dependencies
        run: yarn || "ls"
      - name: Build and Package Mac
        run: yarn package:mac

  build_on_windows:
    name: Build Gosuto on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: 'ls '
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '18.10.x'
      - name: machine echo $HOME
        run: 'echo $HOME'
      - name: Install dependencies
        run: yarn || "ls"
      - name: Build and Package Windows
        run: yarn package:win

  build_on_linux:
    name: Build Gosuto on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: 'ls '
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '18.10.x'
      - name: machine echo $HOME
        run: 'echo $HOME'
      - name: Install dependencies
        run: yarn || "ls"
      - name: Build and Package Linux
        run: yarn package:linux
